### ISSUE TITLE
No Counter.js file ?

### ISSUE THREAD

**Issue by patrickbolle** [Elkfox/shopify-node-app#1]
Is there supposed to be a Counter.js in the /models folder?

**Comment by cam** [comment]
Quite possibly. I'll Look into it and report back. Thanks for reporting!

**Comment by cam** [comment]
@ButsAndCats you noticed a few missing/incorrect requirements, right? Could you take a look at this?

**Comment by georgebutter** [comment]
Sure thing I forgot to make notes so I will have to figure it out again.

**Comment by rgantree** [comment]
Hi There,
Any updates on ./Counter.js file?

Thanks

**Comment by georgebutter** [comment]
Sorry been a bit swamped, will try and take a look tonight.

**Comment by georgebutter** [comment]
@patrickbolle @rgantree 

I have added back in Counter.js, looks like it was in the process of being replaced with sequelize. I haven't had a chance to test this since adding back in. Let me know if you need further assistance.
