### ISSUE TITLE
verifyWebhook fails

### ISSUE THREAD

**Issue by Popesites** [Elkfox/shopify-node-app#10]

**Comment by Popesites** [comment]
verifyWebhook fails altogether. 

First, the X-Shopify-Hmac-SHA256 record is being digested in hex encoding, but Shopify encodes it in base64. 

Also, the data being passed to verifyWebhook from req.body isn't correct. I believe that it needs to be rawBody format. After changing the encoding to base64, the calculatedSignature and the hmac values still do not match. I'm currently trying to find a solution for converting req.body to raw format.

**Comment by Popesites** [comment]
I've got a fix, I will open a PR and set it for review

**Comment by cam** [comment]
Excellent. Thanks @Popesites!
