### ISSUE TITLE
BuildWebhook

### ISSUE THREAD

**Issue by IamNagaraju** [Elkfox/shopify-node-app#12]
Can you show me some example by creating any webhook using buildWebHook. I am not able to get what to write in the callback function. Please help me with this

**Comment by cam** [comment]
@IamNagaraju you should only need to pass a topic to the function. You can see a list of those at https://help.shopify.com/en/api/reference/events/webhook

There's a little more info here: https://elkfox.github.io/shopify-node-app/#helper-functions
