### ISSUE TITLE
Cannot read property 'access_token'

### ISSUE THREAD

**Issue by devenderbutani** [Elkfox/shopify-node-app#14]
Unhandled rejection TypeError: Cannot read property 'access_token' of undefined at shopAPI.exchange temporary token

**Comment by Arvind6353** [comment]
Am getting the same error . Any help on this ?

**Comment by cam** [comment]
@Arvind6353 & @devenderbutani Please take a look at this issue https://github.com/Shopify/shopify-node-app/issues/77

I think that should have the answers you need.
