### ISSUE TITLE
shopify-node-app/routes/install.js - undefined variable on line 63

### ISSUE THREAD

**Issue by jremi** [Elkfox/shopify-node-app#2]
First, I want to say thank you for this great repo you made available. As you wrote on your docs... saved me like 1 million hours of time and I am enjoying. 👍 

Just a small bug that you might want to update since it will cause the redirect sequence to fail after the user installs the app...

Undefined variable **shop.shopify_doman** should be **shop.shopify_domain** 
(missing letter "i")

**Line 63 on install.js** 
[Screenshot](//i.imgur.com/FG8ihgo.png)

**Comment by georgebutter** [comment]
Thanks @jremi
