### ISSUE TITLE
Auto wait after a Shopify Call

### ISSUE THREAD

**Issue by abhishekj** [Elkfox/shopify-node-app#4]
Hi , 

This is a great app and i am liking it much now,

One thing i noticed is that if the number of hits crosses more than Shopify give throttling errors, is there a way to handle it?

and can this be built on in this app?

Please advise,

**Comment by georgebutter** [comment]
Hi,

This app uses the shopify-node-api module. You can find out about the API limiting options here: https://www.npmjs.com/package/shopify-node-api#api-call-limit-options
