### ISSUE TITLE
MongoError: failed to connect to server

### ISSUE THREAD

**Issue by DevCabin** [Elkfox/shopify-node-app#5]
Hey there, I've followed every step on the doc page right up to the first npm start. I left my port at 7777. But I get this error in the console : 
🚫 Database Error 🚫  → MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Running 'mongod' appears to work fine, so I'm at a loss as to why this fails. Obviously I'm not a super JS ninja, any help is appreciated.

**Comment by georgebutter** [comment]
Try checking out this thread: https://stackoverflow.com/questions/13312358/mongo-couldnt-connect-to-server-127-0-0-127017
