### ISSUE TITLE
Add a snippet and css to theme

### ISSUE THREAD

**Issue by sumit-suretek** [Elkfox/shopify-node-app#6]
How we can add a snippets and css file to theme ?

**Comment by georgebutter** [comment]
Sorry, can you expand your question a bit?
Did you want to add CSS to the app view or to a snippet?
What is it that you are trying to achieve?

**Comment by sumit-suretek** [comment]
I want to insert a snippet(html code) in theme using this app. I want to upload some css and js, if this is not possible I can upload in cdn servers. Adding a snippet to theme is very urgent.

**Comment by georgebutter** [comment]
Okay I'll write an article on this soon.
