### ISSUE TITLE
Facing an error while installing the app

### ISSUE THREAD

**Issue by ehsankhakbaz** [Elkfox/shopify-node-app#7]
Thank you for the nice job!

I just cloned and ran the code as per the docs but ran into this error while installing my app on a dev store:
`Unhandled rejection TypeError: Cannot read property 'nonce' of null
      at query.then (~/shopify-node-app/routes/install.js:47:19)`

Can you help?

**Comment by ehsankhakbaz** [comment]
I did found the issue.
routes/install.js (line 11) should be 
`const shopName = `${req.query.shop}`;`

I can commit this if you will.

**Comment by cam** [comment]
@ehsankhakbaz Nice one! Can you please create a PR 👍

**Comment by antwal** [comment]
same problem, the value not is passed

```
router.get('/callback', (req, res) => {
  const params = req.query;
  const query = Shop.findOne({ shopify_domain: params.shop }).exec();
  query.then((result) => {
    const shop = result;
    const shopAPI = new Shopify({
      shop: params.shop,
      shopify_api_key: config.SHOPIFY_API_KEY,
      shopify_shared_secret: config.SHOPIFY_SHARED_SECRET,
      nonce: shop.nonce,
    });
    shopAPI.exchange_temporary_token(params, (error, data) => {
```

shop.nonce is always null

**Comment by cam** [comment]
Fixed in latest update
