### ISSUE TITLE
Create an authenticated rest api for online store

### ISSUE THREAD

**Issue by vmundhra** [Elkfox/shopify-node-app#8]
Hello. 

I have been trying to figure out a way to create an authenticated rest api for shops. i.e. only the store that has installed the app should be able to call the rest endpoint from their online store. I have also set up Application proxy for the app. But its seems like that method, used with "**/proxy**", delivers a liquid template for pages and not JSON. I may be wrong here. All I want to do is that a JavaScript code running inside the online shop (which has installed the app) should be able to call the api and not just any rest client. 

What I understand is "**/api**" route is for front-end components of the app, which will have session or cookie and thus are able to mak ethe call. But what about the online store that has installed my app? 

I hope you understand the problem. Pls help.

Thanks,
Vishal

**Comment by cam** [comment]
Hi @vmundhra. I think you may be looking for the ScriptTag method https://help.shopify.com/en/api/reference/online_store/scripttag
