### ISSUE TITLE
Need examples

### ISSUE THREAD

**Issue by shivaganeshb** [Elkfox/shopify-node-app#9]
Hey Team,

I need some examples to use Webhook and Calling List of Products. Can someone help me please.

**Comment by dlazzy** [comment]
I'm stuck with that too...

Need to only show shop products through the app, so created a route like :

```js
/* GET products page. */
router.get('/show_products', (req, res) => {
  console.log(req.query);

  return res.render('app/products');
});
```

Maybe I've missed something about Shopify app development methods, but the `req.query` is empty.

When opening the app through the admin panel, I can see `You're currently logged in as: myshop.myshopify.com` then going to `show_products` route by a *href*, press go back also with a href and the app is showing `Welcome to Welcome to your example app`. I don't understand everything, I think :sweat: 

Thanks for the help
